### ISSUE TITLE
FR: trigger "battle" vs "selfbattle"

### ISSUE THREAD

**Issue by twilde** [dlowe-net/dawdlerpg#1]
I expected "trigger battle" as an admin to trigger a fully randomized battle, but it triggers a battle with me involved. Perhaps that behavior should be "trigger selfbattle" or something while "trigger battle" follows the regular battle trigger logic like teambattle?

**Comment by dlowe-net** [comment]
Fixed in passing via 73426c51527e58b53c254c725c0ee3bdf698e413.
